### ISSUE TITLE
Cannot create local ftp server without internet

### ISSUE THREAD

**Issue by ruafelianna** [Red-Eyed/python_ftp_server#2]
Hello!

It would be nice to have an opportunity to create a local ftp server (ip=127.0.0.1) while I don't have internet connection. When I am offline I get the following traceback because the module tries to connect to google dns (8.8.8.8) to get local ip (???) even though I set it as 127.0.0.1.

`python3 -m python_ftp_server --ip 127.0.0.1 --port 60000 --user myuser --password mypasswd`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/python_ftp_server/__main__.py", line 10, in <module>
    main()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/python_ftp_server/ftp_server.py", line 95, in main
    parser.add_argument("--ip", type=str, default=get_local_ip())
                                                  ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/python_ftp_server/ftp_server.py", line 33, in get_local_ip
    s.connect(("8.8.8.8", 80))
OSError: [Errno 101] Network is unreachable
```

**Comment by Red-Eyed** [comment]
Hello, thank you for the report!
check it out

**Comment by ruafelianna** [comment]
Thanks, it works!
